apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: transaction-service
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/git-ashu/devops-platform.git
    targetRevision: master
    path: cluster-config/helm/transaction-service

  destination:
    server: https://kubernetes.default.svc
    namespace: apps

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
